"""añadir imagen_url a productos

Revision ID: 4ef9a2c0e1fe
Revises: 2a7784b6138a
Create Date: 2026-03-23 12:31:39.944870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ef9a2c0e1fe'
down_revision: Union[str, Sequence[str], None] = '2a7784b6138a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('imagen_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'imagen_url')
    # ### end Alembic commands ###
