"""add exclusivo to productos

Revision ID: 8cdd28acdcc3
Revises: 79b4a710cdcc
Create Date: 2026-04-13 17:23:51.991927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cdd28acdcc3'
down_revision: Union[str, Sequence[str], None] = '79b4a710cdcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('es_exclusivo', sa.Boolean(), nullable=False))
    op.add_column('productos', sa.Column('fecha_fin_exclusivo', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'fecha_fin_exclusivo')
    op.drop_column('productos', 'es_exclusivo')
    # ### end Alembic commands ###
